influxdata/influx-cli

- go.mod
- pkg/csv2lp/README.md
- pkg/csv2lp/csv2lp.go
- pkg/csv2lp/csv2lp_test.go
- pkg/csv2lp/csv_annotations.go
- pkg/csv2lp/csv_annotations_test.go
- pkg/csv2lp/csv_table.go
- pkg/csv2lp/csv_table_test.go
- pkg/csv2lp/data_conversion.go
- pkg/csv2lp/data_conversion_test.go
- pkg/csv2lp/examples_test.go
- pkg/csv2lp/line_reader.go
- pkg/csv2lp/line_reader_test.go
- pkg/csv2lp/multi_closer.go
- pkg/csv2lp/multi_closer_test.go
- pkg/csv2lp/skip_header_lines.go
- pkg/csv2lp/skip_header_lines_test.go
Part of #25 
`csv2lp` is used for client-side processing of CSV inputs. I've copied it verbatim from `influxdb`.
Code to actually use the module will come in follow-up PRs, but the unit tests here hit 100% coverage in the module according to `go test -cover`
> feat: port csv2lp from influxdb

- cmd/influx/main.go
- pkg/signals/context.go
- pkg/signals/context_test.go
Part of #25 
The 1st commit ports `pkg/signals` verbatim from `influxdb`. The 2nd commit updates our existing commands to use the new context logic.
> feat: use signal-wrapped contexts in CLI commands

- internal/mock/api_health.go
- internal/mock/api_setup.go
- internal/mock/config.go
- internal/ping_test.go
- internal/setup_test.go
I made this cleanup when I first started working on #25 and thought there would be a lot of mocks needed for it. It turned out to not be the case, but I still think this is an improvement in the repo's organization.
> refactor: move mock APIs and services into mock module

- etc/generate-openapi.sh
- internal/api/api_health.go
- internal/api/api_setup.go
- internal/api/client.go
- internal/api/client_internal_test.go
- internal/api/error.go
- internal/api/templates/README.md
- internal/api/templates/api.mustache
- internal/api/templates/client.mustache
- internal/ping.go
- internal/ping_test.go
Part of #25 
* Use `[]byte` for generated request bodies when the source schema has `format: byte`
* Gzip-compress request bodies when `Content-Encoding: gzip` is set
* Add tests to show both gzip and no-gzip work
* Require that all models returned as error conditions in our API implement the `error` interface
* Move the implementation for `api.HealthCheck` out of `ping.go` and into `api/error.go`
> feat(api): improve codegen outputs

- go.mod
- go.sum
- internal/throttler/throttler.go
- internal/throttler/throttler_test.go
Part of #25 
`ToBytesPerSecond` is copied verbatim from `influxdb`. The rest of the logic was factored out of the `createLineReader` function in `cmd/influx/write.go`, for better separation of concerns / easier testing.
> feat: port rate-limiter from influxdb

- internal/linereader/multi_reader.go
- internal/linereader/multi_reader_test.go
Part of #25 
Most of this logic was copied directly from `influxdb`. The differences are:
1. Refactor how stdin / error out / HTTP clients are made available to the logic, for easier testing
2. Split out rate-limiting logic (see #44)
> feat: port line reader from influxdb

- internal/batcher/buffer_batcher.go
- internal/batcher/buffer_batcher_internal_test.go
- internal/batcher/buffer_batcher_test.go
Part of #25 
This is pretty close to a verbatim copy of the `write` module from `influxdb`. Apart from some renamed structs, the main difference is:
* The batcher in `influxdb` was hard-coded to take an HTTP client and call the `/write` API per-batch
* The batcher here takes a generic `writeFn`
> feat: port write-batcher from influxdb

- cmd/influx/main.go
- cmd/influx/ping.go
- cmd/influx/setup.go
- cmd/influx/version.go
Part of #25 
We're starting to port commands that take a large number of flags. Split to a file-per-command to (hopefully) make things more sustainable.
> refactor: split CLI commands into separate files

- internal/ping.go
- internal/setup.go
- internal/write.go
Closes #55 
Tiny refactor to improve our code style while it's still a small surface area.
> refactor: switch to Execute() method on requests

- internal/setup.go
- internal/setup_test.go
Before this change, if a user tried to double-setup their local server they'd see `config name is required if you already have existing configs`. That's technically correct, but IMO the more useful error to see is `instance has already been set up` (it's also the error they'd see in the old CLI).
Rearrange the validation performed by `setup` to make the server-side check run first.
> fix: check server status before local config to improve error message

- Makefile
- go.mod
- internal/api/api_bucket_schemas.gen.go
- internal/api/api_buckets.gen.go
- internal/api/api_health.gen.go
- internal/api/api_organizations.gen.go
- internal/api/api_setup.gen.go
- internal/api/api_write.gen.go
- internal/api/templates/README.md
- internal/api/templates/api.mustache
- internal/bucket.go
- internal/bucket_test.go
- internal/cmd/bucket_schema/client.go
- internal/cmd/bucket_schema/client_test.go
- internal/mock/api_bucket_schemas.gen.go
- internal/mock/api_buckets.gen.go
- internal/mock/api_buckets.go
- internal/mock/api_health.go
- internal/mock/api_organizations.go
- internal/mock/api_setup.go
- internal/mock/api_write.go
- internal/ping.go
- internal/ping_test.go
- internal/setup.go
- internal/setup_test.go
- internal/write.go
- internal/write_test.go
- tools.go
Part of #14
It's hard to see the full picture without adding the `/query` endpoint, but these changes include:
1. When `Content-Encoding: gzip` is set on a response, gunzip the request body before attempting any processing
2. When a request has `format: binary` in its top-level response schema, bypass the logic that pulls the full response into memory
* Instead return the `io.ReadCloser` from the `http.Response` (or the gunzip-wrapped body) directly
3. Remove the `*http.Response` from the set of return values generated for every operation
* Prevents a confusing "which do I use?" situation where we return both the HTTP response body as an `io.ReadCloser` and the `*http.Response` containing a reference to the same body
* Cleans up a lot of code, because we were never using the raw return …
> refactor: improve codegen to support `influx query` rewrite

- cmd/influx/query.go
- internal/cmd/query/formatting_printer.go
- internal/cmd/query/formatting_printer_test.go
- pkg/fluxcsv/query_result.go
- pkg/fluxcsv/query_result_test.go
- pkg/fluxcsv/table.go
- pkg/fluxcsv/table_test.go
Closes #14 
The implementation here is a blend of existing code from other projects & my adaptations.
* `pkg/fluxcsv` is an adaptation of the query-result data structures & parsers from [`influxdata/influxdb-client-go`](https://github.com/influxdata/influxdb-client-go/)
* I adjusted the logic to properly parse where new query results/tables start, instead of assuming a new table starts any time there's a new set of annotation rows
* `formatting_printer.go` is an adaptation of [this code](https://github.com/influxdata/influxdb/blob/master/cmd/influx/query.go#L216-L493) from `influxdb`, which itself was copy-pasted from [this file](https://github.com/influxdata/flux/blob/master/execute/format.go) in `flux`.
* Apart from adapting to the new types in `pkg/fluxcsv`, I tried to simplify some of …
> feat: add formatted output to `influx query`

- pkg/csv2lp/csv2lp.go
- pkg/csv2lp/csv2lp_test.go
Closes #106 
A warning is printed if `influx write` processes a CSV header line with a CR character that is not followed by LF character:
```
2021/06/05 20:24:58 WARNING: line 1: standalone CR character found. Only CRLF and LF line endings are supported.
```
Such warning helps to quickly recognize an input file with exotic line endings (#106). `influx write` as well as golang's CSV parser recognizes properly only LF (unix) and CRLF (windows) line endings. The fix also applies to `influx write dryrun`.
> feat(write): warn about standalone CR characters in header lines

- clients/backup/backup_internal_test.go
Parallel tests were calling `log.SetOutput`. I considered making the tests run sequentially, but I think there are suites in other packages that also modify the global `log` state and I didn't want to just push the problem down the road. Asserting on the log output is something I feel ok not doing.
> test: remove racy logic from backup test

- api/api_backup.gen.go
- api/api_bucket_schemas.gen.go
- api/api_buckets.gen.go
- api/api_delete.gen.go
- api/api_health.gen.go
- api/api_organizations.gen.go
- api/api_query.gen.go
- api/api_restore.gen.go
- api/api_setup.gen.go
- api/api_tasks.gen.go
- api/api_users.gen.go
- api/api_write.gen.go
- api/templates/README.md
- api/templates/api.mustache
This will make POST-ing files w/ gzip slightly more convenient, since we can plug a `ReadCloser` directly into the request instead of writing a temp file.
> refactor: use io.ReadCloser instead of **os.File for binary request params

- clients/export/export.go
- clients/export/out.go
- clients/export/resource.go
- cmd/influx/export.go
Part 2/3 of #12 
Most of the diff is moving around code from the top-level `export` command.
> feat: port `export all` command from `influxdb`

- cmd/influx/main.go
- cmd/influx/v1_commands.go
- cmd/influx/v1_dbrp.go
Part of #23 & #24
This PR adds a placeholder for `v1` subcommands. They can be linked into the CLI via the `newV1SubCommand` function.
If the `newV1SubCommand` function needs to be in its own folder could be discussed - I started with it there since that is how it is in the `influxdb` codebase: https://github.com/influxdata/influxdb/blob/master/cmd/influx/v1_commands.go
> feat: placeholder for v1 subcommands

- go.mod
- go.sum
- pkg/template/color.go
- pkg/template/diff_printer.go
- pkg/template/diff_printer_test.go
- pkg/template/table_printer.go
- pkg/template/table_printer_test.go
Part of #4
The diff-printer is a near-direct copy from [this code](https://github.com/influxdata/influxdb/blob/master/cmd/influx/template.go#L1787-L1939) in `influxdb`. The table-printer's [core logic](https://github.com/influxdata/influxdb/blob/master/cmd/influx/template.go#L1941-L1994) is also from `influxdb`, but I refactored it to have the same structure as the diff-printer.
> feat: port table-printers from influxdb

- clients/apply/source.go
- clients/apply/source_test.go
- pkg/github/normalize.go
- pkg/github/normalize_test.go
Part of #4
`influx apply` supports reading templates from files, urls, and stdin. This is my attempt to hide these differences behind some sort of common interface.
This isn't a 1:1 match to the code from `influxdb` (I tried to clean it up some, and added tests). The original code is:
* [Here](https://github.com/influxdata/influxdb/blob/master/cmd/influx/template.go#L1027-L1066)
* [Here](https://github.com/influxdata/influxdb/blob/master/pkger/parser.go#L45-L266) (minus the logic around "source" content-type, because the derivation didn't actually work as far as I could tell)
> feat: port template-parsing logic from influxdb

- clients/errors.go
- clients/export/export.go
- cmd/influx/export.go
Closes #12 
Ports over the `export stack` subcommand from the influxdb repo, with modified logic to work with openapi/codegen. Usage of this command is `export stack [flags] <stack_id>`. Note that it will not currently work with the usage `export stack <stack_id> [flags]`.
> feat: port influx export stack subcommand

- clients/helpers.go
- cmd/influx/backup.go
- cmd/influx/bucket.go
- cmd/influx/bucket_schema.go
- cmd/influx/completion.go
- cmd/influx/config.go
- cmd/influx/dashboards.go
- cmd/influx/delete.go
- cmd/influx/export.go
- cmd/influx/global.go
- cmd/influx/main.go
- cmd/influx/org.go
- cmd/influx/org_members.go
- cmd/influx/ping.go
- cmd/influx/query.go
- cmd/influx/restore.go
- cmd/influx/secret.go
- cmd/influx/setup.go
- cmd/influx/task.go
- cmd/influx/telegrafs.go
- cmd/influx/user.go
- cmd/influx/v1_auth.go
- cmd/influx/v1_commands.go
- cmd/influx/v1_dbrp.go
- cmd/influx/version.go
- cmd/influx/write.go
- go.mod
- go.sum
- pkg/cli/middleware/middleware.go
Closes #147
I've confirmed that rebasing #150 onto this branch fixes the breaking change (I can pass the stack ID before or after the `-f` flag).
> fix: downgrade urfave/cli to v1 to enable more flexible parsing

- clients/bucket_schema/client.go
- clients/bucket_schema/create_test.go
- clients/bucket_schema/list_test.go
- clients/bucket_schema/update_test.go
This PR ensures that either the `--bucket-id` or `-i` CLI options are permitted for the `bucket-schema` commands. It adds complete test coverage for all the `bucket-schema` commands to ensure the CLI options are permitted in all combinations.
Fixes #149
> fix: Accept bucket ID or bucket name arguments

- api/api_authorizations.gen.go
- api/api_backup.gen.go
- api/api_bucket_schemas.gen.go
- api/api_buckets.gen.go
- api/api_dashboards.gen.go
- api/api_dbrps.gen.go
- api/api_delete.gen.go
- api/api_health.gen.go
- api/api_legacy_authorizations.gen.go
- api/api_organizations.gen.go
- api/api_query.gen.go
- api/api_restore.gen.go
- api/api_secrets.gen.go
- api/api_setup.gen.go
- api/api_tasks.gen.go
- api/api_telegrafs.gen.go
- api/api_templates.gen.go
- api/api_users.gen.go
- api/api_write.gen.go
- api/templates/api.mustache
Closes #156
Some tweaks to the error message string formatting and return value for API call responses which are able to successfully be parsed (they are valid JSON), but are a status code outside the 200 range, indicating some kind of problem processing the request. This applies to API's flagged as Cloud- or OSS- only.
The error messages documented by #140 continue to be generated identically with this change, but this also adds the additional info text to errors such as trying to run a backup command against a cloud server which did not work as intended with #140:
```
influx backup .
2021/06/30 10:16:48 INFO: Downloading metadata snapshot
Error: failed to backup metadata: failed to download metadata snapshot: path not found
```
becomes:
```
influx backup .    
2021/06/30 10:15:53 INFO: …
```
> fix: cloud or oss only error msg for parsable responses

- clients/apply/apply.go
- clients/apply/source.go
- clients/apply/source_test.go
- cmd/influx/apply.go
- cmd/influx/main.go
- internal/mock/stdio.gen.go
- pkg/stdio/console.go
- pkg/stdio/stdio.go
Closes #4
The logic here isn't a 1:1 match. At the parsing layer, I changed:
* `--template-url / -u` is now un-deprecated
* Passing a HTTP(s) URL to `--file / -f` is now deprecated
* Malformed values passed to `--env-ref / --secret / --filter` now result in an error instead of being silently dropped
Within the core logic, the CLI code no longer knows how to summarize templates. Because of this:
* The CLI locates all missing env & secret refs by POST-ing a dry-run to the server and inspecting the returned summary
* To display an accurate diff, the CLI posts a 2nd dry-run after collecting all missing env/secret values, and uses the result of _that_ to render the diff table
* The 2nd dry-run is skipped if there are no missing values
> feat: port `apply` command from `influxdb`

- api/api_stacks.gen.go
- api/contract/overrides/paths/stacks_stack_id.yml
Merging #165 and #163 in sequence broke our `openapi` CI check because I didn't re-generate in-between to pick up the new error logic. This re-generates everything, and also fixes the bad strings I missed in #165.
> chore: fix up openapi codegen after multi-merge

- api/api_templates.gen.go
- api/contract/overrides/paths/templates_apply.yml
- api/contract/overrides/schemas/TemplateSummaryError.yml
- api/error.go
- api/model_template_summary_error.gen.go
- api/model_template_summary_variable_args_render.go
- clients/apply/apply.go
- clients/template/template.go
- cmd/influx/apply.go
- cmd/influx/main.go
- cmd/influx/template.go
- pkg/template/source.go
- pkg/template/source_test.go
- pkg/template/summary_printer.go
Closes #21
This isn't a 1:1 port from the code in `influxdb`:
* The old CLI performed summarization / validation completely on the client-side, reusing the code that the server runs when parsing `apply` requests
* This implementation POSTs a dry-run `apply` to the server and parses the response to replicate the behavior without needing to reimplement all the server logic in the new repo
I sanity-checked with @russorat before taking the new approach.
> feat: implement `template` command

- clients/setup/setup.go
In support of influxdata/influxdb#21838, also make the `OnboardingRequest` method public so it can be reused.
> refactor: expose method for building onboarding requests

- clients/restore/restore.go
And this is why automated tests are a good thing...
> fix: set content-encoding: gzip for non-legacy KV restore

- clients/stacks/stacks.go
Closes #196 
Makes `stacks --json` print a bare array instead of `{ "stacks": [] }`. This matches the 2.0.x output. It's also consistent with `bucket list`, `org list`, and `task list` (and I assume others, but those are the ones I spot-checked).
> fix: make `stacks --json` output match 2.0.x

- pkg/stdio/console.go
Closes #201
New behavior in action:
> fix: retry password-prompt if 2nd entry doesn't match the 1st

- cmd/influx/global.go
Making the env var match what's used in the old CLI
> fix: fix env var used for configs path

- CHANGELOG.md
- cmd/influx/global.go
This PR binds the `--skip-verify` flag to the `INFLUX_SKIP_VERIFY` environment variable. This allows a user to omit specifying the flag for every invocation of the `influx` command, and is particularly useful when using the `influx` command in development environments.
> feat: Bind skip-verify flag to INFLUX_SKIP_VERIFY

- Makefile
- go.mod
- go.sum
I was curious what might get flushed out by the upgrade, but looks like there weren't any lurking issues. Upgrading lets us get rid of the `go mod vendor` requirement, which is nice.
> build: upgrade staticcheck to latest version

- CHANGELOG.md
- cmd/influx/global.go
> fix: make `--http-debug` flag visible in help text

- CHANGELOG.md
- clients/auth/auth.go
- clients/auth/auth_internal_test.go
> fix: don't set empty strings for IDs in permission resources

- go.mod
- go.sum
When upgrading kapacitor to go1.17 I saw a panic from `go-isatty`, and tracked it down to `golang.org/x/sys`. golang/go#47279 says the bug has been fixed, so upgrading should prevent future panics.
I couldn't trigger the panic in the CLI but it does use `go-isatty`, so upgrading feels like a smart move.
> fix: upgrade golang.org/x/sys to avoid panics on Macs

- CHANGELOG.md
- clients/setup/setup.go
- clients/setup/setup_test.go
- cmd/influx/setup.go
Closes #253
The previous behavior would wrongly copy the host of the currently-active config to the newly-generated config.
> fix: --host value passed to setup is written to generated config

- Makefile
Make targets may call '$(GO_BUILD)', but there is no facility for
specifying arguments to 'go build'. As a first step, introduce the
GCFLAGS Makefile variable that when unset, operates as always, but when
set, adds '-gcflags "$(GCFLAGS)"' to go build. Eg, when unspecified,
maintain the current behavior (though with an additional space):
```
$ make
CGO_ENABLED=0 go build  -ldflags ...
```
When specified, add the specified -gcflags:
```
$ GCFLAGS="all=-N -l" make
CGO_ENABLED=0 go build -gcflags "all=-N -l" -ldflags ...
```
This could be useful in various situations such as producing unoptimized
builds (like in the above).
> chore(Makefile): allow specifying -gcflags via env

- CHANGELOG.md
- cmd/influx/global.go
> fix: fix type test for common flags

- clients/remote/remote.go
- cmd/influx/remote.go
Closes #241 
This command will list all remote connections for an org. Optionally, a user can also specify a remote connection name or remote URL to filter results and only list those connections which fit the criteria.
> feat: added functionality for `remote list` subcommand

- api/client.gen.go
- api/templates/client.mustache
For some use-cases (i.e. sending a no-op write request) it's useful to be able to specify a body of `[]byte{}`. This refactors our codegen template to allow that.
> fix: allow explicit empty request bodies

- api/configuration.gen.go
- clients/remote/remote.go
- cmd/influx/remote.go
Closes #244 
This command deletes an existing remote connection. Remote ID is the only flag, and it is required.
> feat: added functionality for `remote delete` command

- cmd/influx/remote.go
Import of `fmt` in `remote` cmd code was no longer necessary after two recent merges. This should resolve the current cross-build failure in CircleCI.
> fix: removed unused `fmt` import in `remote` cmd code

- clients/replication/replication.go
- cmd/influx/replication.go
Closes #246 
The `replication create` subcommand registers a new replication stream. This configures an existing bucket to replicate all future points to one or more remote InfluxDB instances. 
**Required Flags**
`--name, -n` (Name for new replication stream)
`-- remote-id` (Remote connection the new replication stream should send data to)
`--local-bucket` (ID of local bucket data should be replicated from)
`--remote-bucket` (ID of remote bucket data should be replicated to)
**Optional Flags**
`--description, -d` (Description for new replication stream)
`--org-id` (The ID of the local organization)
`--org, -o` (The name of the local organization)
`--max-queue-bytes` (Max queue size in bytes, default 67108860)
**Note:** A user would need to start with a registered remote connection before …
> feat: added functionality for `replication create` command

- clients/replication/replication.go
- cmd/influx/remote.go
- cmd/influx/replication.go
Closes #248 
This command deletes an existing replication stream, given its ID. This command will also delete data still in the stream, if any. `id` is the only option for this command, and it is required.
**Note:** This PR also changes the naming of the `remote-id` flag for `remote update` and `remote delete` subcommands.
`--remote-id, -id` --> `--id, -i`
This was done to maintain consistency with other `influx` CLI commands.
> feat: added functionality for replication delete command

- .circleci/config.yml
- .goreleaser.yml
- CHANGELOG.md
- scripts/ci/build-tests.sh
- scripts/ci/run-prebuilt-tests.sh
- scripts/ci/run-race-tests.sh
Closes #304
This PR was originally meant to be build-only, aligning a piece of the `influx-cli` CI setup with `influxdb`. In the process I rediscovered golang/go#38453. We work around that issue here in the same way we did in influxdata/influxdb#22447, setting a build tag when `GOOS=windows` so TZ data is embedded in the binary.
> fix: embed tzdata into Windows builds

- CHANGELOG.md
- clients/org/org_members.go
- clients/org/org_members_test.go
> fix: wrong position of orgID and userID in `org members remove`

- api/client.gen.go
- api/configuration_default.go
- api/templates/client.mustache
Influxdata cloud2 uses a different mechanism to enable tracing.
You need to pass a `influx-debug-id` header (the value is ignored) and if the response contains
`trace-sampled: true` then the response's `trace-id` header contains a valid trace ID that can be
used to jump to the trace in jaeger.
If the request has been sampled, we print the trace-id to stderr.
Since modern terminals allow to click on hyperlinks, we could avoid a copy&paste of the trace id
if the `influx` binary wrote a the link to the jeager trace.
However, we don't want to hardcode the URL of the internal jaeger endpoint in the binary.
I tried adding a wrapper script on my machine that would just capture the trace-id and render it, but it's
hard to do without messing with the ordering of the stderr and stdout lines.
Thus I …
> fix: Use influx-debug-id header

- pkg/duration/parser.go
Closes #171
Before: 
```
influx bucket update -i 853de12dd738bd7d -r 11234 
Error: duration is missing a unit: 
```
After:
```
influx bucket update -i 853de12dd738bd7d -r 11234            
Error: duration is missing a unit: 11234
```
> fix: duration parser shows duration missing units on error

- clients/apply/apply.go
- cmd/influx/apply.go
- pkg/template/diff_printer.go
- pkg/template/diff_printer_test.go
fix: when statestatus is 'remove', mark as removed
fix: template apply uses better diff checking
Closes: https://github.com/influxdata/influx-cli/issues/233
Previously, we did a DeepEqual of all the returned data about each changed entity,
but due to our template overrides that is not actually all the information
available for each entity. So we marked trivial things as 'conflicts' (e.g.
telegraf config ID's 'changing' from the empty string to the real, current value)
while not catching important conflicts like flux script changes in checks and tasks.
Changes to make things more straightforward:
* Change the --force behaviour to be more similar to `apt install`, where even
in non-interactive mode `--force yes` is required to bypass the prompt to apply.
* Before, there were two stages of …
> fix: template apply uses better diff checking

- clients/remote/remote.go
Improves error logging for setting up a new remote connection.
Alternatively this could have been done as a different error returned from the server, but this should be sufficient to display errors more clearly.
> chore: improve logging for creating a new remote

- pkg/template/source.go
- pkg/template/source_test.go
Closes https://github.com/influxdata/influx-cli/issues/351
The server can reject jsonnet files due to security concerns, so don't pretend that our files are jsonnet templates.
> fix: json suffix for json template from CLI

- api/api_write.gen.go
- api/model_replication_creation_request.gen.go
- api/model_replication_update_request.gen.go
- clients/replication/replication.go
- cmd/influx/replication.go
Adds the max age fields to the `replications create` and `replications update` commands.
Part of https://github.com/influxdata/influxdb/issues/23109
> feat: add max age to replications create and update

- cmd/influx/global.go
- cmd/influx/util.go
- cmd/influx/util_go117.go
Some influxdb feature flags can be controlled by headers; let's add a way to play with those headers without forcing us back into raw `curl`.
> feat: Add --extra-http-header flag

- cmd/influx/apply.go
- cmd/influx/auth.go
- cmd/influx/backup.go
- cmd/influx/bucket.go
- cmd/influx/dashboards.go
- cmd/influx/export.go
- cmd/influx/global.go
- cmd/influx/query.go
- cmd/influx/remote.go
- cmd/influx/secret.go
- cmd/influx/stacks.go
- cmd/influx/task.go
- cmd/influx/telegrafs.go
- cmd/influx/template.go
- cmd/influx/user.go
- cmd/influx/v1_auth.go
- cmd/influx/v1_dbrp.go
- cmd/influx/write.go
Environment variables did get correctly overridden by the command line flags already, but the problem was when a user would pass the `-o` flag (or `INFLUX_ORG` env var) and the `INFLUX_ORG_ID` env var (or `--org-id` flag), it wasn't made clear that only the OrgId was being used. OrgName would be ignored.
Now, any command that uses the org flags enforces only one can be used, not both.
When both flags are passed together, the user will see an error like this: 
```
Error: ambiguous org: use OrgId or OrgName, but not both. OrgID: 844910ece80be8bc, OrgName: 9c5955fc99a60b8f
```
Closing #371
> fix: add mutual exclusion for OrgId and OrgName params

- .circleci/config.yml
> build: upgrade to Go 1.18.3

- clients/auth/auth.go
- clients/auth/auth_internal_test.go
Closes #293 
Users and Orgs permissions shouldn't be scoped under a specific organization, this fixes that.
> fix: users and orgs permissions should not be scoped under an org

- cmd/influx/main.go
- cmd/influx/main_test.go
This is a pretty awkward problem, and it stems from the fact that those wrapping quotes are parsed away when Go gets the program's arguments for `os.Args`.
I ran `dlv debug ./cmd/influx -- config create -n targetflux -u "http://localhost:8087" -o "organization" -t "-therestofmytoken"`
And this is the `os.Args` value which `urfave/cli` uses directly.
```
(dlv) p os.Args
[]string len: 11, cap: 11, [
"...+2 more",
"config",
"create",
"-n",
"targetflux",
"-u",
"http://localhost:8087",
"-o",
"organization",
"-t",
"-therestofmytoken",      <--- no wrapping quotes
]
```
It seems like a bespoke method specifically for replacing `-t "-FOO-TOKEN"` with `-t=-FOO-TOKEN` in `os.Args` before passing into `urfave/cli` makes the most sense here.
Closing #376 and #378
> Replace token flags with = to prevent bad parsing of leading dash in token

- clients/v1_shell/v1_shell.go
> chore: fix up tabs vs. spaces mistakes in help prompt

- clients/v1_shell/autocomplete.go
- clients/v1_shell/table_model.go
- clients/v1_shell/v1_shell.go
- go.mod
- improves string formatting so that EXPLAIN ANALYZE format looks correct
- adds right alignment for number types, and left alignment for string (no more quotes as well)
- adds `scientific` command to toggle decimal vs. scientific numeric format when using table format.
- enter altscreen when running table interactive mode to improve scroll appearance. 
Closes #405
> fix: improve alignment for strings and numbers in v1 shell

- .circleci/config.yml
- .circleci/scripts/upload-latest-artifacts
When a release is triggered, this uploads the release packages as both `influxdb2-client-<version>` and `influxdb2-client-latest`.
> build: upload "latest" artifacts

- api/api_invokable_scripts.gen.go
- api/api_tasks.gen.go
- api/api_users.gen.go
- api/api_write.gen.go
- api/contract/cli.yml
- api/model_label.gen.go
- api/model_post_organization_request.gen.go
- api/model_script_create_request.gen.go
- api/model_task.gen.go
- api/model_task_create_request.gen.go
- api/model_task_status_type.gen.go
- api/model_task_update_request.gen.go
- clients/task/task.go
This PR updates the openapi submodule to include the new invokable scripts from tasks functionality for the cloud. The CLI commands have not been updated to allow access to the new features yet.
Note since the tasks api is available to both OSS and cloud, but they have different features available, the cloud yaml takes priority for generation.
> feat: updated openapi to support tasks containing scripts

- clients/remote/remote.go
- clients/replication/replication.go
- cmd/influx/remote.go
https://github.com/influxdata/influxdb/pull/23493 removed replication configs deleting automatically when remotes are deleted. This PR reimplements that feature, but only if you pass the `--delete-replications` flag to the `influx remote delete` command
> feat: allow deleting replications with remotes

- clients/task/task.go
- cmd/influx/task.go
This PR adds invokable script functionality to the task create command, which is only available for the cloud. Tested on OSS and cloud, OSS will ignore the flags marked as cloud-only.
closes https://github.com/influxdata/influx-cli/issues/407
> feat: added script support when creating tasks for the cloud

- clients/task/task.go
- cmd/influx/task.go
This PR adds invokable script functionality to the task update command, which is only available for the cloud. Tested on OSS and cloud, OSS will ignore the flags marked as cloud-only.
Also properly print the script ID when tasks are listed in table format.
closes https://github.com/influxdata/influx-cli/issues/408, closes https://github.com/influxdata/influx-cli/issues/409, closes https://github.com/influxdata/influx-cli/issues/410
> feat: added script support when updating tasks for the cloud

- cmd/influx/auth.go
Fixes the `--read-remotes`, `--write-remotes`, `--read-replications`, and `--write-replications` flags from being hidden in `influx auth create -h`
These flags currently work if used, though are not displayed in help text or documentation
> fix: show `remotes` and `replications` flags in `auth create`

- .circleci/config.yml
CircleCI was erroring:
```
Build-agent version 1.0.134103-8a9e13ee (2022-08-02T13:24:16+0000)
Creating a dedicated VM with xcode:12.4.0 image
failed to create host: Image xcode:12.4.0 is not supported
failed to create host: Image xcode:12.4.0 is not supported
```
This PR updates to the latest supported version.
> fix: update unsupported xcode version

- clients/v1_dbrps/v1_dbrps.go
- clients/v1_dbrps/v1_dbrps_test.go
- cmd/influx/v1_dbrp.go
- Add new help info about virtual DBRPs for `influx v1 dbrp list -h` 
- Split `influx v1 dbrp list` into physical and virtual DBRP tables
> Clarify difference in virtual vs physical dbrps when listing

- clients/stacks/stacks.go
Spotted this typo whilst investigating a stack issue and is a simple fix in an error returned to the user.
> fix(stacks): Fix stack error typo

- api/response.gen.go
- etc/generate-openapi.sh
5.1.1 introduced arm images so now the build is not terribly slow on Apple Silicon Macs.
> chore: update generator image

- go.mod
- go.sum
Closes #482
This enables builds on RISCV.
> chore: version bump sys to support riscv

- scripts/ci/build-packages
The package filename remains "influxdb2-client"; however, internally the package has been renamed to "influxdb2-cli". This is so upgrades are performed correctly by apt and yum (which use the package metadata rather than the filename).
This also swaps out underscores to slashes to match what influxdata-docker expects.
> fix: rename package to influxdb2-cli

- clients/signin/signin.go
Hi,
It is possible to have multiple cookies returned on a successful sign-in response, specially when it is running behind a reverse proxy etc. This PR fixes the issue by looking up the cookies that contain `influxdb` within the name (it works on both OSS and cloud) and using the value of that cookie instead of checking for cookie array size.
> fix(signin): Check for all available cookies instead of the count

- .circleci/config.yml
The release-nightly workflow was failing as it was attempting to import the old signing key. This PR removes that statement as well as correctly supplies the "DEBIAN_FRONTEND" environment variable to the "apt-get" commands.
> fix: don't import non-existent/unused GPG private key

- .circleci/config.yml
Currently, binaries built from CI report "dev" instead of the correct version information. This updates the CI config so that "COMMIT" and "VERSION" are supplied at compile time.
> fix: supply "VERSION" and "COMMIT" to Makefile

- clients/setup/setup_test.go
- pkg/stdio/stdio.go
Disable password length checks and let `influxd` 
do all password strength checks.  
closes https://github.com/influxdata/influx-cli/issues/533
> fix: disable passord length checks so influxdb validates passwords

- clients/setup/setup_test.go
- pkg/stdio/stdio.go
Disable password length checks and let influxd
do all password strength checks.
closes https://github.com/influxdata/influx-cli/issues/533
(cherry picked from commit df2e6877b68c2d55c97af20879a65be9ebf5237d)
closes https://github.com/influxdata/influx-cli/issues/535
> fix: disable passord length checks so influxdb validates passwords (#534)

- .circleci/config.yml
Fixes CVE-2024-24790, reported by X-Ray.
Fixes #544
> chore: upgrade to go 1.21.12

- clients/v1_shell/table_model.go
- clients/v1_shell/table_model_test.go
Fixes #547
Fixes #542
Currently, when the method `func (m Model) Init()` is called on a result containing a tag with an empty value (e.g. `"tags":{"state":""}`), the program panics on the line (`fmt.Print(tagline[:len(tagline)-2])`).
in `table_modle.go` when the method `func (m Model) Init()` is called with a result containing a tag with an empty value (e.g. `"tags":{"state":""}`), the empty value is substituted in the tea model with a default presentation string ` ----- ` suggesting an empty value was found.
> fix: avoid panic on empty tag value

- clients/restore/restore.go
- cmd/influx/restore.go
Add `--operator-token` flag to restore subcommand. If the backup being restored lacks a plaintext operator token, then the token given with `--operator-token` will be used to restore the backup.
> feat: add `--operator-token` flag to restore subcommand
