influxdata/influx-cli

internal/config/config.go, internal/config/local.go
Unrelated fixes I found while working on #25
=> fix: fix some issues with the local config service

cmd/influx/main.go, internal/cli.go, internal/ping.go, internal/ping_test.go, internal/setup.go, internal/setup_test.go, internal/write.go, internal/write_test.go
=> refactor: inject trace ID as a default header

cmd/influx/config.go, cmd/influx/main.go, cmd/influx/setup.go, internal/cmd/config/config.go, internal/cmd/config/config_test.go
Closes #9
Most of the interesting logic was already implemented in the local config service
=> feat: port `influx config` from `influxdb`

cmd/influx/main.go, cmd/influx/org.go, etc/generate-openapi.sh, internal/cmd/org/client.go, internal/cmd/org/org.go, internal/cmd/org/org_test.go
Part of #13 
Not very interesting, CRUD logic + printing
=> feat: port top-level `org` commands from `influxdb`.

.gitignore
Small PR, that simply adds `.idea/` to `.gitignore`
=> chore: add .idea/ to gitignore

.circleci/config.yml, Makefile, pkg/signals/context_test.go, scripts/ci/install-go.sh, scripts/ci/setup-system.sh
Closes #26
Closes #27 
Closes #28
=> build: run tests natively on ARM, Mac, and Windows in CI

clients/backup/backup.go, clients/backup/backup_internal_test.go, clients/backup/manifest.go, clients/backup/manifest_test.go, clients/restore/manifest.go, clients/restore/restore.go, cmd/influx/backup.go, cmd/influx/main.go, cmd/influx/restore.go, internal/backup_restore/manifest.go
Closes #15
I've manually tested that this works, but still need to write some unit tests for the more interesting pieces of logic.
=> feat: implement `influx restore` using new APIs

clients/restore/restore.go
* Properly handle 404 returned by get-orgs API
* Set correct org ID and name when restoring bucket manifests
=> fix: fix bugs in new `influx restore` impl

clients/apply/source.go, pkg/github/normalize.go, pkg/github/normalize_test.go
=> fix: fix extension-check logic when normalizing github URLs

api/api_backup.gen.go, api/api_restore.gen.go, api/contract/cli.yml, api/model_task.gen.go, internal/mock/api_backup.gen.go
All codegen (trying to keep the later diffs small)
=> feat: update codegen to include legacy backup/restore routes

clients/backup/backup.go, clients/backup/backup_internal_test.go, clients/restore/restore.go, cmd/influx/backup.go, internal/backup_restore/manifest.go
=> feat: update `backup` to support InfluxDB 2.0.x

clients/restore/restore.go
Closes #193
Confirmed that this fixes the problem for me locally.
=> fix: upload uncompressed boltdb when doing legacy full-restore

clients/user/user.go, clients/user/user_test.go, cmd/influx/user.go
=> feat: allow passing password via flag in `user password`

.goreleaser.yml
=> build: rename deb/rpm package to more closely match existing `influxdb2`

CHANGELOG.md, cmd/influx/main.go
=> fix: enable default completion logic on top-level app

.circleci/config.yml
=> build: prefix nightly versions with latest tag

api/api_restore.gen.go, api/contract/cli.yml
Follow-up to influxdata/openapi#177
=> refactor: use updated API in restore client

Makefile, clients/secret/secret_test.go, pkg/github/normalize_test.go, pkg/gzip/pipe_test.go, pkg/template/source_test.go
=> build: fix `make fmt`, reformat test sources

CHANGELOG.md, cmd/influx/apply.go, cmd/influx/auth.go, cmd/influx/bucket.go, cmd/influx/bucket_schema.go, cmd/influx/config.go, cmd/influx/dashboards.go, cmd/influx/delete.go, cmd/influx/export.go, cmd/influx/org.go, cmd/influx/org_members.go, cmd/influx/ping.go, cmd/influx/secret.go, cmd/influx/setup.go, cmd/influx/stacks.go, cmd/influx/task.go, cmd/influx/telegrafs.go, cmd/influx/template.go, cmd/influx/user.go, cmd/influx/v1_auth.go, cmd/influx/v1_dbrp.go, cmd/influx/version.go, pkg/cli/middleware/noargs.go, pkg/cli/middleware/noargs_test.go
=> fix: detect and error out on incorrect positional args

CHANGELOG.md, go.mod, pkg/signals/context_test.go, scripts/ci/install-go.sh, tools.go
=> build: upgrade to go1.17

CHANGELOG.md, clients/setup/setup.go, clients/setup/setup_test.go, cmd/influx/setup.go
=> fix: --host value passed to setup is written to generated config

CHANGELOG.md, clients/apply/apply.go, clients/auth/auth.go, clients/cli.go, clients/secret/secret.go, clients/secret/secret_test.go, clients/stacks/stacks.go, clients/telegrafs/telegrafs.go, clients/template/template.go, clients/user/user.go, clients/user/user_test.go, clients/v1_auth/v1_auth.go, cmd/influx/global.go
=> fix: less confusing overloads of 'token' in help

CHANGELOG.md, clients/restore/restore.go, cmd/influx/restore.go
Partial fix for https://github.com/influxdata/influxdb/issues/20749
=> fix: restore when changing tokens works

CHANGELOG.md, cmd/influx/auth.go, cmd/influx/bucket.go, cmd/influx/bucket_schema.go, cmd/influx/main.go, cmd/influx/org.go, cmd/influx/org_members.go, cmd/influx/remote.go, cmd/influx/replication.go, cmd/influx/secret.go, cmd/influx/task.go, cmd/influx/user.go, cmd/influx/v1_auth.go, cmd/influx/v1_commands.go, cmd/influx/v1_dbrp.go
=> fix: return "unknown command" instead of "no help topic" error when unknown (sub)command is passed

clients/org/org_members.go, clients/org/org_members_test.go
=> fix: 🐛 wrong position of orgID and userID

clients/v1_auth/v1_auth.go
=> fix: v1 auth create command supports multiple buckets

api/model_replication.gen.go, api/model_replication_creation_request.gen.go, api/model_replication_update_request.gen.go, clients/replication/replication.go, clients/replication/replication_test.go, cmd/influx/replication.go
Part of https://github.com/influxdata/influxdb/issues/22880
Also see: https://github.com/influxdata/influxdb/pull/22885
=> feat: add `drop-non-retryable-data` to replications commands

api/api_remote_connections.gen.go, api/contract/cli.yml
Related to https://github.com/influxdata/influxdb/pull/22901
Not much to do here since the remote validation stuff wasn't ever added to the CLI, but this does update the openapi submodule and remove the path.
=> chore: remove remote validation

cmd/influx/remote.go, cmd/influx/replication.go
=> feat: enable remotes and replication streams feature

README.md
Add instructions for updating openapi to the influx-cli README.
=> update: instructions to update openapi

api/error.go, api/model_authorization.gen.go, api/model_authorization_all_of.gen.go, api/model_authorization_post_request.gen.go, api/model_authorization_update_request.gen.go, api/model_dbrp.gen.go, api/model_dbrp_create.gen.go, api/model_error.gen.go, api/model_legacy_authorization_post_request.gen.go, api/model_line_protocol_error.gen.go, api/model_line_protocol_length_error.gen.go, api/model_measurement_schema.gen.go, api/model_measurement_schema_column.gen.go, api/model_measurement_schema_create_request.gen.go, api/model_task.gen.go, config/config.go, config/local.go
Updates the CLI to the latest OpenAPI spec, primarily updating to changes made in https://github.com/influxdata/openapi/pull/263
=> chore: upgrade to latest OpenAPI

clients/v1_shell/table_model.go, clients/v1_shell/v1_shell.go
Closes https://github.com/influxdata/influxdb/issues/23587 and https://github.com/influxdata/influx-cli/issues/429
=> fix: prevent shell hang on empty query result

cmd/influx/main.go
Closes #329 and probably would help https://github.com/influxdata/influx-cli/issues/422.
=> Add influx command shell hint

api/api_tasks.gen.go, clients/task/task.go, cmd/influx/task.go
This pr enables support for looking up tasks by a script id.
Closes #411
=> chore(tasks): support looking up tasks by script id

clients/auth/auth.go, cmd/influx/auth.go
Part of https://github.com/influxdata/influxdb/issues/23668
=> fix: don't allow creating an auth with instance resources

cmd/influx/task.go
Closes https://github.com/influxdata/influxdb/issues/23672
=> fix: fixes an error where stdin could not be used to create tasks

clients/bucket_schema/csv.go, clients/bucket_schema/csv_test.go, clients/bucket_schema/testdata/columns.csv
Closes https://github.com/influxdata/influx-cli/issues/450
=> fix: cloud expects dataType in csv files

clients/task/task.go
=> fix: handle "every" when defined inside of flux

go.mod, go.sum
=> chore: update go-prompt to fix terminal clear issue

.circleci/config.yml, api/api_authorizations.gen.go, api/api_backup.gen.go, api/api_bucket_schemas.gen.go, api/api_buckets.gen.go, api/api_config.gen.go, api/api_delete.gen.go, api/api_invokable_scripts.gen.go, api/api_legacy_authorizations.gen.go, api/api_organizations.gen.go, api/api_ping.gen.go, api/api_signin.gen.go, api/api_tasks.gen.go, api/api_users.gen.go, api/api_write.gen.go, scripts/ci/download-goreleaser.sh, scripts/ci/install-go.sh
=> chore: update to go 1.19 (#465)

api/model_error_code.gen.go
This pulls in the change to add the NotImplemented error code which will improve error reporting on `influx delete`
=> chore: update openapi

pkg/csv2lp/lp_reader.go, pkg/csv2lp/lp_reader_test.go
closes https://github.com/influxdata/influx-cli/issues/502
=> fix: handle line protocol wrap with --skipRowOnError

pkg/csv2lp/lp_reader.go, pkg/csv2lp/lp_reader_test.go
closes https://github.com/influxdata/influx-cli/issues/502
(cherry picked from commit b29425c7609abbccf5b66518a3aa93624bf16bb3)
closes https://github.com/influxdata/influx-cli/issues/537
=> fix: handle line protocol wrap with --skipRowOnError (#536)
